### ISSUE TITLE
images are not pulled; rivanna/singularity

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/bulker#33]
I get the following error on Rivanna:
```
[mjs5kd@udc-ba36-36 bulker](dev): bwa
ERROR  : Image path /home/mjs5kd/simages/quay.io/biocontainers/bwa:0.7.17--pl5.22.0_2 doesn't exist: No such file or directory
ABORT  : Retval = 255
```
It worked on my laptop

I'm using the `dev` version of `bulker` and just initalized the configuration. 

It looks like it does not proceed to image pulling in this case

**Comment by michalstolarczyk** [comment]
running with `-b` and `-r` flags helped. But still, it's something to investigate

**Comment by nsheff** [comment]
yes -- singularity does not pull by default, you have to specify `-b` to get it to work.

it is possible to make it happen automatically by changing the exec template.
