### ISSUE TITLE
bulker overrides default shell

### ISSUE THREAD

**Issue by lwaldron** [databio/bulker#39]
For example, zsh is the default shell in the newest OSX update, so you a) get the following message, and b) lose your zsh settings such as custom prompt in favor of `bulker-3.2$`. I also noticed the loss of custom shell settings before the zsh migration.

```
10:37:58 wallabe:~/git > echo $SHELL
/bin/zsh
10:37:59 wallabe:~/git > bulker activate demo   
Bulker config: /Users/lwaldron/bulker_config.yaml
Activating bulker crate: demo


The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bulker-3.2$ 
```

**Comment by nsheff** [comment]
it will now use the default shell. you can change it in the new `shell_path` attribute in the bulker config, which defaults to:

```
shell_path: ${SHELL}
```

you can also do something like this to specify on the fly:

```
SHELL=/bin/sh bulker activate...
```
