### ISSUE TITLE
associating many commands with a container

### ISSUE THREAD

**Issue by lwaldron** [databio/bulker#54]
Question - is there a shortcut for associating many commands with a container? For example, see https://github.com/databio/hub.bulker.io/blob/master/waldronlab/metagenomics.yaml. The approach I used there of just repeating over many lines in the crate works fine, I just thought I'd check.

**Comment by nsheff** [comment]
Not possible at the moment.

I've thought about this before... but the format would need a way to map each exposed command to a container command, so I didn't go down that route and thought it simpler to just repeat, as you have done.

we _could_ devise some format that would be container-centric, and then list all command mappings or something.

**Comment by lwaldron** [comment]
Probably not worth much effort, since the current solution isn’t bad. I’ll write a loop to copy out the repetition if I want to associate many more commands than this to a container.
