### ISSUE TITLE
line 3: docker: command not found

### ISSUE THREAD

**Issue by ccrobertson** [databio/bulker#80]
Hi Nathan,

I am working on updating my PEPATAC installation on Rivanna (last time I installed it was in Nov 2019). I see it now uses bulker to handle containers. I have installed bulker and loaded the pepatac container using the following from the pepatac documentation:

bulker load databio/pepatac:1.0.4 -r
bulker activate databio/pepatac:1.0.4

however, when i then try to run commands (e.g. the pepatac example, or even "cat filename" to look at a file), i get the error

/home/ccr5ju/bulker_crates/databio/pepatac/1.0.4/cat: line 3: docker: command not found

I'm guessing this has to do with the fact that Rivanna does not support docker. Is there an option I need to provide to indicate that singularity must be used instead?

Thanks for the help!

**Comment by ccrobertson** [comment]
UPDATE:

This error message also happens with the bulker demo example:


> bulker activate demo
Using default config. No config found in env var: BULKERCFG
Bulker config: /home/ccr5ju/.local/lib/python3.6/site-packages/bulker/templates/bulker_config.yaml
Activating bulker crate: demo
/home/ccr5ju/.local/lib/python3.6/site-packages/bulker/bulker.py:762: UserWarning: The '_file_path' property is deprecated and will be removed in a future release. Use YacAttMap["__internal"][_file_path] instead.
  os.path.dirname(bulker_config._file_path))
\[\033[01;93m\]bulker/demo|\[\033[00m\]\[\033[01;34m\]\w\[\033[00m\]\$

> bulker/demo|~/software$ cowsay "hello"
/home/ccr5ju/bulker_crates/bulker/demo/default/cowsay: line 3: docker: command not found

**Comment by nsheff** [comment]
Hi, did you run a `bulker init` at all? it should automatically detect that you have only singularity installed and work, but you'd need to initialize.

If you didn't `bulker init` to create your own config, then bulker may be using the default config, which defaults to `docker`.

**Comment by ccrobertson** [comment]
UPDATE 2: 

I used the autogeneration of the config file using `bulker init -c $BULKERCFG` as described here: 
https://bulker.databio.org/en/latest/install/

This works now! Before I had manually edited the container engine field in the provided config file, but not very carefully.

Sorry for the trouble!
